<?xml version="1.0" encoding="utf-8"?><Database Name="Test" Class="TestDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=Test;Persist Security Info=True;User ID=sa" SettingsObjectName="linq.Properties.Settings" SettingsPropertyName="TestConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ajaxTest" Member="ajaxTest">
    <Type Name="ajaxTest">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TestName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TestNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>